
;  PlatformIO — Bare-Metal ATmega328P (Versi Simulasi)
;  NO Arduino framework, NO external libraries


[env:uno]
platform  = atmelavr
board     = uno
framework =               ; kosong = bare-metal (no framework)

; --- Monitor ---
; Kecepatan baudrate tetap disamakan dengan fungsi uart_init() di kode C Anda (9600)
monitor_speed = 9600

; Build flags: F_CPU wajib didefinisikan manual karena tidak ada Arduino framework
build_flags =
    -DF_CPU=16000000UL
    -mmcu=atmega328p
    -Os
    -std=gnu++11
    -fno-exceptions
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections