; =====================================================
;  PlatformIO — Bare-Metal ATmega328P
;  NO Arduino framework, NO external libraries
; =====================================================

[env:uno]
platform  = atmelavr
board     = uno
framework =               ; kosong = bare-metal (no framework)

; Upload
upload_port     = COM4
upload_protocol = arduino  ; pakai bootloader bawaan Uno (optiboot)

; Monitor
monitor_port  = COM4
monitor_speed = 9600
monitor_dtr   = 0
monitor_rts   = 0

; Build flags: F_CPU wajib didefinisikan manual karena tidak ada Arduino
build_flags =
    -DF_CPU=16000000UL
    -mmcu=atmega328p
    -Os
    -std=gnu++11
    -fno-exceptions
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections

; Tidak ada lib_deps — semua driver ditulis di main.cpp